### ISSUE TITLE
CC is running fine but not CC UI

### ISSUE THREAD

**Issue by chetann** [linkedin/cruise-control-ui#4]
Hi Team,

I am able to run CC on my local machine and able to see data on 9090 for CC but when I deploy CC UI, I end up getting this error. Anything that needs to be done, can you kindly help me out.
``` ERROR  Failed to compile with 1 errors                                                                                                                                                5:24:44 PM

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://0.0.0.0:8090```
When I hit CC UI service on 8090, I do get `Cannot GET /`

**Comment by nareshv** [comment]
@chetann whats the version of nodejs/npm thats installed ?

**Comment by chetann** [comment]
Hi @nareshv strange. I had installed latest version but when I open my terminal it shows up 
```node -v
v6.11.0```
But on the shell tab where I am running CC UI it is showing up as 
```node -v
v10.15.1```
Anything that I am missing out here.

**Comment by nareshv** [comment]
what do you get for `npm ls | grep eslint ; npm -v` ?

**Comment by chetann** [comment]
@nareshv 
```
$ npm ls | grep eslint ; npm -v
3.10.10
```

**Comment by nareshv** [comment]
@chetann can you grab the latest code from master and run `npm install && npm run dev` again ? I have added `package-lock.json` which makes sure there are right dependencies installed before building.

I have also pushed a release[1] which you can deploy within cruise-control folder and modify `static/config.csv` if required.

structure for deployment should be

```
cruise-control/
              /cruise-control-ui/
                               /dist/
                                   /index.html
                                   /static/config.csv
                                   /static/cc-logo.png
                                   /static/js/*
                                   /static/css/*
```

[1] https://github.com/linkedin/cruise-control-ui/releases/download/v0.1.0/cruise-control-ui.tar.gz

**Comment by chetann** [comment]
I did download the latest master branch @nareshv and did `npm install && npm run dev` but still getting the same error as mentioned earlier.
``` 
ERROR  Failed to compile with 1 errors                                                                                                                                                2:43:09 PM

Module build failed: Error: No ESLint configuration found.
    at getLocalConfig (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint/lib/cli-engine.js:754:26)
    at lint (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/Users/z076952/Documents/Data_movement_git/cruise-control-ui/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://0.0.0.0:8090
```
I saw your release, should I untar it and use/replace it somewhere?
https://github.com/linkedin/cruise-control-ui/releases/download/v0.1.0/cruise-control-ui.tar.gz

**Comment by chetann** [comment]
To give in more light into this issue. @nareshv 
I have my CC running in a different folder then that off CC-UI. I guess this should be fine right.
I am following below steps
1. Start Zk/Kafka - Status both running.
2. Start CC - Status running.
3. Then I change the config file to `local,localhost,http://localhost:9090/kafkacruisecontrol/` 
and run this `npm install && npm run dev`
That is when I end up running into the issue.

**Comment by chetann** [comment]
@nareshv is there anything that you can help me on.

**Comment by nareshv** [comment]
@chetann Since CCFE is just a web app and there are multiple ways to set it up.  i'd suggest to go with easier option to begin with

Few suggestions for you.

1. Do not go with the npm (build / run dev) route as i suspect you are having older versions of node/npm causing issues.
2. Follow the above directory structure (https://github.com/linkedin/cruise-control-ui/issues/4#issuecomment-464548460 ) and directly leverage the webserver thats part of CC to access the Frontend (ie. after your 1 & 2 steps, hitting http://localhost:9090/ will show CCFE) -- Embedded mode. (No need to run npm here, just download artifacts and put them inside CC)

Let me know if you encounter any further issues in this approach.

**Comment by nareshv** [comment]
@chetann , i have created a wiki for guidance https://github.com/linkedin/cruise-control-ui/wiki/Single-Kafka-Cluster

**Comment by chetann** [comment]
@nareshv Thanks a lot for the document shared and single cluster set up worked very fine.
We have around 20-30 kafka clusters running on cloud and when I read the multi kafka cluster, didn't get much on it. It mentions that, multiple instances of CC-UI running with multiple URL's. Like how can I club them all or get all running on a single URL?
Can you kindly be bit more clear on this area.
https://github.com/linkedin/cruise-control-ui/wiki/Multiple-Kafka-Cluster

**Comment by nareshv** [comment]
@chetann , i just finished writing this https://github.com/linkedin/cruise-control-ui/wiki/Multiple-Kafka-Clusters

**Comment by nareshv** [comment]
@chetann , let us know if you need any other help.

**Comment by chetann** [comment]
@nareshv Thanks a lot for quick responses. I am new to webserver set up and those area. I could follow most of the stuffs you mentioned in Multiple kafka cluster but not sure of this `Make these changes in the appropriate Apache server <Directory> path.` How do I get this path.
I have my config file for apache2 running here `/usr/local/etc/httpd/httpd.conf` is this the Directory path you mentioning off. Can you kindly help me in this section.

**Comment by nareshv** [comment]
@chetann , `httpd` has something called as `DocumentRoot` which should be the place where you can deploy the `cruise-control-ui/dist/*` files.

You will also have a `VirtualHost` section Configured which can have its own `DocumentRoot`. See https://httpd.apache.org/docs/2.4/vhosts/examples.html for examples.

**Comment by chetann** [comment]
@nareshv Thanks. I was able to connect do the multiple cluster set up and able to see the UI but it is unable to connect to the CC running on other pods. So basically my CC runs on different pods and CCUI is one new pod, with the steps mentioned I have mentioned I added all entries.
I am able to do a curl call in the CCUI pod to hit the CC endpoint and getting response. But from the UI I am getting network error. anything that rings your mind. Can you kindly help me.

<img width="1376" alt="screen shot 2019-03-02 at 12 28 42 am" src="https://user-images.githubusercontent.com/3926813/53659705-35f25600-3c82-11e9-87ac-6ab8d8074d32.png">

**Comment by nareshv** [comment]
@chetann 

This is the flow

```
{Browser}(CCFE) <--> {Webserver} <--> CC1..CCN
```

There are 2 ways your browser (CCFE App) can reach the CC, which is determined by the URLs in the `config.csv`

1. If you are using absolute urls in config.csv, then you need to go with additional configuration on all CCs (CORS Method)
2. If you are using relative urls in config.csv, then all requests made by browser will go through Webserver where CCFE is deployed (as webserver will connect to CC and send data back to browser).

I suspect you are using method-1, thats why you are getting `network error`

See https://engineering.linkedin.com/blog/2019/02/introducing-kafka-cruise-control-frontend for description of these 2 methods and how connections are made.

As of now CC doesn't support native HTTPS, If you are using any sidecar proxy, then only its possible to get HTTPS with CC.

Since CCFE is a webapp, make sure you serve this over HTTPs in case you are planning to connect to the backends over HTTPs or else you get into errors. I'd recomment to read [1] to understand more about this.

[1] https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by chetann** [comment]
@nareshv Thanks for all the suggestions in detail. I was able to launch it in k8 overcoming the CORS issue, had to add the CORS Enable section in CC Control Servlet post which I was able to get the response.

One of things I noticed throughout testing is, the cookies issue. The UI holds onto old details such as CC UI links or sometimes the dropdown from which we select the cluster to be used does not update even though config.csv is updated. Unless cleared manually. Is there anything that can be done? Frequently clearing cookies is one overhead I felt.

You can feel free to close this issue if otherwise.

**Comment by nareshv** [comment]
@chetann , CC is moving towards User Tasks and Cookies have caused troubles for us in the past as well. There is minor patch pending in CC to support User Tasks in CORS method, once this is done you should have good CORS experience.

Meanwhile i'll also create a wiki explaining how to setup CORS method with CCFE.

As per current design, `config.csv` is fetched once during application startup and is not refreshed later. I'll add a task to do periodic refresh of this `config.csv` to avoid confusion.

**Comment by chetann** [comment]
Yes I agree documentation would help lot of users especially with CORS stuff, 
refreshing config.csv is needed as thats where new updates are failing. 

Meanwhile to overcome CORS issue, this is what I have added this section in servlet section in CC source code for doGet and doPost methods. Sharing with you in case if this helps the documentation. Will shortly raise a PR on CC source code as well.
https://github.com/linkedin/cruise-control/blob/master/cruise-control/src/main/java/com/linkedin/kafka/cruisecontrol/servlet/KafkaCruiseControlServlet.java
```
if (_corsEnabled) {
      response.setHeader("Access-Control-Allow-Credentials",
              "true");
      response.setHeader("Access-Control-Allow-Origin",
                         _config.getString(KafkaCruiseControlConfig.WEBSERVER_HTTP_CORS_ORIGIN_CONFIG));
      // This is required only as part of pre-flight response
      response.setHeader("Access-Control-Request-Method",
                         _config.getString(KafkaCruiseControlConfig.WEBSERVER_HTTP_CORS_ALLOWMETHODS_CONFIG));
    }
  }
```
Will be closing this issue @nareshv Thanks again. Will reach out to you in case I find anything while going through UI in detail.
